"""Storage abstraction. JSONL is the built-in backend; the protocol keeps
future backends (SQLite, Postgres, S3, ...) pluggable."""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Protocol, runtime_checkable

from slomo._core.events import Event
from slomo._core.session import SessionMeta


@runtime_checkable
class SessionWriter(Protocol):
    def write_event(self, event: Event) -> None: ...
    def flush(self, *, fsync: bool = False) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class StorageBackend(Protocol):
    # write side
    def create_session(self, meta: SessionMeta) -> SessionWriter: ...
    def finalize_session(self, session_id: str, meta_updates: dict[str, Any]) -> None: ...
    def write_attachment(self, session_id: str, name: str, data: bytes) -> str: ...

    # read side
    def list_sessions(self) -> list[SessionMeta]: ...
    def read_session_meta(self, session_id: str) -> SessionMeta: ...
    def iter_events(self, session_id: str, *, from_offset: int = 0) -> Iterator[Event]: ...
    def delete_session(self, session_id: str) -> None: ...
